# This is a sample build configuration for Java (Maven).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: maven:3.6.1

pipelines:
  default:
    - step:
        caches:
          - maven
        script: # Modify the commands below to build your repository.
          - cd backend
          - mvn -B verify # -B batch mode makes Maven less verbose
    - step:
        name: Deploy to production
        deployment: test
        script:
          - pipe: atlassian/google-app-engine-deploy:0.6.0
            variables:
              KEY_FILE: '<string>'
              PROJECT: '<string>'
              # DEPLOYABLES: '<string>' # Optional
              # VERSION: '<string>' # Optional.
              # BUCKET: '<string>' # Optional.
              # IMAGE: '<string>' # Optional.
              # PROMOTE: '<boolean>' # Optional
              # STOP_PREVIOUS_VERSION: '<boolean>' # Optional.
              # EXTRA_ARGS: '<string>' # Optional.
              # DEBUG: '<boolean>' # Optional.
              # CLOUD_BUILD_TIMEOUT: '<integer>' # Optional
